export default {
  FETCH_SCIFI: "FETCH_SCIFI",
  FETCH_FANTASY: "FETCH_FANTASY",
  FETCH_HORROR: "FETCH_HORROR",
  FETCH_ANIMATION: "FETCH_ANIMATION",

  FETCH_SEARCH: "FETCH_SEARCH",
  FETCH_THEMOVIE: "FETCH_THEMOVIE",

  CLEAR_THE_MOVIE: "CLEAR_THE_MOVIE",
  CLEAR_SEARCH_RESULT: "CLEAR_SEARCH_RESULT",

  LOGIN_USER: "LOGIN_USER",
  REGISTER_USER: "REGISTER_USER",
  USER_LOGOUT: "USER_LOGOUT",

  LOGIN_ADMIN: "LOGIN_ADMIN",
  ADMIN_LOGOUT: "ADMIN_LOGOUT",

  UPLOAD_MOVIE: "UPLOAD_MOVIE",
  ENABLE_MOVIE: "ENABLE_MOVIE",
  DISABLE_MOVIE: "DISABLE_MOVIE",
  DELETE_MOVIE: "DELETE_MOVIE",
  FETCH_ALL_MOVIES: "FETCH_ALL_MOVIES",
  FETCH_USER_MOVIES: "FETCH_USER_MOVIES",
  CLEAR_USER_MOVIES: "CLEAR_USER_MOVIES",

  FETCH_INVIDAPI_ERROR: "FETCH_INVIDAPI_ERROR"
};
